### PR TITLE
Prefer latest versions rather than minor ones

### PR DESCRIPTION
**Pull request by dfcreative**
Replaced dependency versions to take latest/major ones.
This is especially the case for packages like `process`, which have some issues fixed, unlike the provided 0.7.0 version.

### CODE REVIEW

**Comment by michaelficarra** [comment]
Might as well use `*` then.

**Comment by dfcreative** [comment]
@michaelficarra Yes, but technically it would be wrong since older versions aren’t supported. It may cause collision if you have already installed older version of dependency (e. g. `process`), which will be kept in that case.

**Comment by AndreasMadsen** [comment]
I don't think this is a good idea. A `major+minor` version of `node-browser-builtins` should reflect a `major+minor` of node.js. If we do this it will cause problem in the transition period between two node releases (e.g. `0.10.x` to `0.12.x`.).

**Comment by dfcreative** [comment]
@AndreasMadsen This PR has nothing to do with version of `node-browser-builtins`, why is that?

**Comment by AndreasMadsen** [comment]
Say you install version `3.2.x` of node-browser-builtins, you should expect this to mimic node 0.10. Doing
`npm install browser-builtins@3.2.0` will then install `buffer@2.4.x` which also mimic node 0.10.

In the transition period between node 0.10 and 0.12, users will want to select the node version node-browser-builtins mimic, so we will release a `4.0.0` or whatever version of node-browser-builtins which does so, this will depend on `buffer@3.0.x` which is fine.

However if we merge this change, then installing the current version of node-browser-builtins there mimic node 0.10 will also install `buffer@3.0.x`, this is is a problem because this version mimics node 0.12, thus we no longer have a version of node-browser-builtins there mimic node 0.10.

**Comment by dfcreative** [comment]
@AndreasMadsen that makes sense providing that all the dependencies strictly mimics version 0.10 of node. But as far, for example, `process@0.7.0` fails to do so: it’s `.version` is undefined, which breaks mimicking any version at all.
If to follow the logic of semver, bumping minor version shouldn’t break backward compatability. So taking the latest compatible deps shouldn’t break stuff. (https://github.com/dfcreative/node-browser-builtins/commit/39bd218c6d106092b10a017da9f163e3db3e81cb)
Also why not to take `3.3.0` for updated deps?

**Comment by dfcreative** [comment]
@alexgorbatchev ?

**Comment by alexgorbatchev** [comment]
If my code is relying on `node-browser-builtins` to have `buffer@2.4.x`, when `buffer@3` is released, that can break my code. This PR opens us up for this possibility.

Curious what problem are you trying to solve? If it's just the `process` being out of date, can we just update that?

**Comment by dfcreative** [comment]
@alexgorbatchev this won’t break your code, since only`buffer@2.x` will be taken - the latest minor unbreaking version.
Yes, you probably could update only `process`, but looking to updates of submodules - there's a lot of things been fixed. Why to keep intentionally older buggy dependencies? If you afraid it might break dependents - it will actually do the opposite. Besides, the concern of exact module is to handle own dependencies, not the dependents.
Though it’s up to you. I suggest releasing `3.3.0`.

**Comment by AndreasMadsen** [comment]
@dfcreative You work under an assumption that people follow semver strictly, I highly doubt that is true.

**Comment by dfcreative** [comment]
@AndreasMadsen so what’s your point then? Never update?

Even current deps style `~0.0.0` uses semver assumption: you can’t guarantee that some dependent lib won’t go pearshape after some patch.

**Comment by AndreasMadsen** [comment]
@dfcreative I will be more than happy to take major+minor updates to our `package.json`. I don't know why you think we won't update our dependencies.

There are plenty of examples of people there don't use semver strictly. For example when we updated to `2.0.0` there where lots of complaint that it broke backwards compatibility. Well of cause it broke backwards compatibility it was a major there updated modules to mimic node 0.10.

I'm not going to contribute more to this discussion. I think you have gotten plenty of opportunity to make your case and you don't seam to provide any new arguments. I will leave it to @alexgorbatchev.

**Comment by dfcreative** [comment]
@AndreasMadsen oh well, got you.

**Comment by AndreasMadsen** [comment]
Closing this for the reasons listed here: https://github.com/rvagg/npm-explicit-deps#-is-dangerous

**Pull request closed without merging**
